FROM @make:docker_base_image@

STOPSIGNAL SIGTERM

ENV provisioning_core_docker_image_home=/opt/provisioning-core

ENV provisioning_core_docker_image_setup_root=/var/local/workspaces/provisioning-core/setup

##

USER    root
WORKDIR "${provisioning_core_docker_image_setup_root}"

COPY ./ "${provisioning_core_docker_image_home}"/
RUN  mv "${provisioning_core_docker_image_home}"/test/* .
RUN  rm -rf "${provisioning_core_docker_image_home}"/test

RUN ./provision.sh docker

##

USER    root
WORKDIR "${provisioning_core_docker_image_setup_root}"

ENTRYPOINT ["sh", "start.sh"]

##

